# Generated by Django 3.2.3 on 2021-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
