# Generated by Django 3.2.3 on 2021-05-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=50),
        ),
    ]
