# Generated by Django 3.2.3 on 2021-05-18 18:09

from django.db import migrations, models
import django.db.models.deletion
import items.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20210516_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.utils.get_user_upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_of_drop', models.DecimalField(decimal_places=2, max_digits=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Case', to='cases.case')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemInCase', to='items.item')),
            ],
        ),
    ]
