# Generated by Django 3.2.3 on 2021-05-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterModelOptions(
            name='itemincase',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
