# Generated by Django 3.2.3 on 2021-06-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210519_1907'),
        ('cases', '0004_case_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='itemincase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsincase', to='items.item'),
        ),
    ]
